movieserial/urls.py
from django.urls import path
from .views import (SerialDetailsView, MovieDetailsView, SerialGanerView, MovieGanerView, ActorsView, ActorDetailsView, ContactUsView,
    AllMoviesView, AllSerialsView
    )


app_name = 'media'
urlpatterns = [
    path('movie/', AllMoviesView.as_view(), name='movies'),
    path('serial/', AllSerialsView.as_view(), name='serials'),
    path('serial/<str:slug>/', SerialDetailsView.as_view(), name='serial-details'),
    path('movie/<str:slug>/', MovieDetailsView.as_view(), name='movie-details'),
    path('serial/ganer/<str:slug>/', SerialGanerView.as_view(), name='serial-ganer'),
    path('movie/ganer/<str:slug>/', MovieGanerView.as_view(), name='movie-ganer'),
    path('actors', ActorsView.as_view(), name='actors'),
    path('actor/<int:id>/', ActorDetailsView.as_view(), name='actor-details'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
]

netmovie/urls.py
# For statics
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from user.views import LoginView, SignupView, logoutView
from movieserial.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='home'),
    path('logout', logoutView, name='logout'),
    path('dashboard/', include('user.urls')),
    path('', include('movieserial.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

# import Views
from .views import (ProfileView, ChangePasswordView, BuySubscriptionView, HistorySubscriptionView, TicketSupportView,
                    TicketDetailsView, RequestView, DashboardView)


app_name = 'dashboard'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('buy-subscription/', BuySubscriptionView.as_view(), name='buy-subscription'),
    path('history-subscription/', HistorySubscriptionView.as_view(), name='history-subscription'),
    path('ticket/', TicketSupportView.as_view(), name='ticket'),
    path('ticket/<int:ticket_id>/', TicketDetailsView.as_view(), name='ticket-details'),
    path('request/', RequestView.as_view(), name='request'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

movieserial/models.py
from django.db import models
from django.contrib.contenttypes import fields, models as c_model
from django.core.validators import MaxValueValidator, MinValueValidator
from user.models import User
from functools import partial


def folder_finder(instance, filename, folder):
    class_name = instance.__class__.__name__.lower()
    _type = 'movies' if class_name == 'movie' else 'serials'
    folder_path = f'images/{_type}/{folder}/{filename}'
    return folder_path


class Actor(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    photo = models.ImageField(upload_to='images/actor/', blank=True, verbose_name='عکس')
    imdb_link = models.URLField(blank=True, verbose_name='ادرس imdb')

    class Meta:
        verbose_name = 'بازیگر'
        verbose_name_plural = 'بازیگر ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Ganers(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    slug = models.SlugField(unique=True, verbose_name='اسلاگ')

    class Meta:
        verbose_name = 'ژانر'
        verbose_name_plural = 'ژانر ها'
        ordering = ['name']


    def __str__(self):
        return self.name


class BaseMedia(models.Model):
    name = models.CharField(max_length=300, verbose_name='نام')
    persian_name = models.CharField(max_length=200, verbose_name='نام فارسی')
    ganers = models.ManyToManyField(Ganers, verbose_name='ژانر ها')
    description = models.CharField(max_length=500, blank=True, verbose_name='درباره')
    stars = models.ManyToManyField(Actor, blank=True, verbose_name='ستارگان')
    info = models.CharField(max_length=200, blank=True, verbose_name='جزیات')
    baner = models.ImageField(upload_to=partial(folder_finder, folder='baner'), verbose_name='عکس فیلم')
    background_baner = models.ImageField(upload_to=partial(folder_finder, folder='backgrounds'), blank=True, verbose_name='بک گراند')
    slug = models.SlugField(unique=True, verbose_name='اسلاگ')
    trailer = models.URLField(blank=True, verbose_name='تریلر')
    online_play = models.URLField(blank=True, verbose_name='لینک تماشای انلاین')
    imdb_link = models.URLField(blank=True, verbose_name='لینک(ارجاع به  imdb)')
    year_create = models.IntegerField(verbose_name='سال ساخت')
    duration = models.TimeField(verbose_name='زمان')
    release_date = models.DateTimeField(verbose_name='زمان پخش')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')
    is_subtitle = models.BooleanField(default=True, verbose_name='زیرنویس')
    is_sound_translate = models.BooleanField(default=False, verbose_name='دوبله')
    point = models.DecimalField(
                                max_digits=4,
                                decimal_places=2,
                                validators=[
                                    MaxValueValidator(10.0,),
                                    MinValueValidator(0.0)
                                    ],
                                verbose_name='امتیاز imdb'
                                )


    class Meta:
        abstract = True
        ordering = ['name']


    def __str__(self):
        return self.name


class DownloadLink(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    link = models.URLField(verbose_name='لینک دانلود مستقیم')
    size = models.BigIntegerField(verbose_name='اندازه')
    is_subtitle = models.BooleanField(default=True, verbose_name='زیرنویس')
    subtitle_types = (('nosub', 'بدون زیرنویس'), ('subsoft', 'subsoft'),)
    subtitle_type = models.CharField(max_length=150, choices=subtitle_types, verbose_name='نوع زیرنویس')
    is_persian_sound = models.BooleanField(verbose_name='صدای فارسی')

    class Meta:
        verbose_name = 'لینک دانلود'
        verbose_name_plural = 'لینک های دانلود'
        ordering = ['id']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Quality(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    episodes = models.ManyToManyField(DownloadLink, verbose_name='قسمت ها')

    class Meta:
        verbose_name = 'کیفیت'
        verbose_name_plural = 'کیفیت ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Section(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    qualitys = models.ManyToManyField(Quality, verbose_name='کیفیت ها')
    status_types = (('creating', 'درحال تولید'),('completed', 'تکمیل شده'), ('canceled', 'کنسل شده'))
    status = models.CharField(max_length=150, choices=status_types, verbose_name='وضعیت')

    class Meta:
        verbose_name = 'بخش'
        verbose_name_plural = 'بخش ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Serial(BaseMedia):
    sections = models.ManyToManyField(Section, blank=True, verbose_name='بخش ها')
    last_episod = models.CharField(max_length=200, verbose_name='آخرین قسمت')
    last_section = models.ForeignKey(Section, blank=True, null=True, on_delete=models.CASCADE, related_name='last_section', verbose_name='آخرین فصل')

    class Meta:
        verbose_name = 'سریال'
        verbose_name_plural = 'سریال ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Movie(BaseMedia):
    qualitys = models.ManyToManyField(Quality, verbose_name='کیفیت ها')

    class Meta:
        verbose_name = 'سینمایی'
        verbose_name_plural = 'سینمایی ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class BaseComment(models.Model):
    text = models.TextField(verbose_name='متن')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر ارسال کننده')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')
    is_spoil = models.BooleanField(default=False, verbose_name='نظر حاوی اسپویل')



class MovieComment(BaseComment):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='سینمایی')
    parent_comment = models.ForeignKey('MovieComment', on_delete=models.CASCADE, null=True, blank=True, verbose_name='کامنت پرنت')

    class Meta:
        verbose_name = 'کامنت فیلم'
        verbose_name_plural = 'کامنت های فیلم'


    def __str__(self):
        return f'{self.user.__str__()}: {self.id}'



class SerialComment(BaseComment):
    serial = models.ForeignKey(Serial, on_delete=models.CASCADE, verbose_name='سریال')
    parent_comment = models.ForeignKey('SerialComment', on_delete=models.CASCADE, null=True, blank=True, verbose_name='کامنت پرنت')


    class Meta:
        verbose_name = 'کامنت سریال'
        verbose_name_plural = 'کامنت های سریال'


    def __str__(self):
        return f'{self.user.__str__()}: {self.id}'


class ContactUs(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام')
    phone = models.BigIntegerField(verbose_name='شماره')
    email = models.EmailField(blank=True, verbose_name='ایمیل')
    subject = models.CharField(max_length=200, verbose_name='موضوع')
    message = models.TextField(verbose_name='متن پیام')


    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'تماس با ما'

    def __str__(self):
        return self.name

movieserial/forms.py
from django import forms
from .models import MovieComment, SerialComment, ContactUs
from user.forms import input_full_dark_attrs, checkbox_attrs


input_full_zinc = {'class': 'input-full-dark simple-input bg-zinc-900'}
class BaseCommentFrom(forms.ModelForm):
    class Meta:
        fields = ['text', 'parent_comment', 'is_spoil']

        widgets = {
            'text': forms.Textarea(attrs=input_full_dark_attrs),
            'parent_comment': forms.NumberInput(attrs=input_full_dark_attrs),
            'is_spoil': forms.CheckboxInput(attrs=checkbox_attrs),
        }

        error_messages = {
            'text': {
                'required': 'این فیلد اجباری است',
            }
        }
    

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


    def save(self, commit = True):
        obj = super().save(commit = False)
        obj.user = self.user
        if hasattr(self, 'serial'):
            obj.serial = self.serial
            print(f'ss{self.cleaned_data["parent_comment"]}')
            try:
                comment = SerialComment.object.get(id = self.cleaned_data['parent_comment'])
                print(comment)
                obj.parent_comment = comment
            except:
                pass
        elif hasattr(self, 'movie'):
            obj.movie = self.movie
            try:
                comment = MovieComment.object.get(id = self.cleaned_data['parent_comment'])
                obj.parent_comment = comment
            except:
                pass
        if commit:
            obj.save()
        return obj


class SerialCommentForm(BaseCommentFrom):
    class Meta(BaseCommentFrom.Meta):
        model = SerialComment


    def __init__(self, *args, **kwargs):
        self.serial = kwargs.pop('serial', None)
        super().__init__(*args, **kwargs)


class MovieCommentForm(BaseCommentFrom):
    class Meta(BaseCommentFrom.Meta):
        model = MovieComment


    def __init__(self, *args, **kwargs):
        self.movie = kwargs.pop('movie', None)
        super().__init__(*args, **kwargs)


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"
    
        widgets = {
            'name' : forms.TextInput(attrs=input_full_zinc),
            'phone': forms.NumberInput(attrs=input_full_zinc),
            'email': forms.EmailInput(attrs=input_full_zinc),
            'subject': forms.TextInput(attrs=input_full_zinc),
            'message': forms.Textarea(attrs=input_full_zinc)
        }

templates/movieserial/base_site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title_page|default:'NetMovie' }}</title>
    <link rel="stylesheet" href="{% static 'css/main_site.css' %}">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css">

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css">

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css">

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css">

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css">

    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css">
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
<body dir="rtl" class="bg-black text-slate-100">
    <div >
        <div class="{% if page_name in 'serial-details,movie-details' %} h-[600px] {% else %} h-[100px] {% endif %} justify-end relative overflow-hidden">
            {% if page_name in 'serial-details,movie-details' %}

            <img class="absolute lg:w-9/12 h-[650px]" src="{% if object.background_baner %} {{ object.background_baner.url }} {% else %} {% endif %}" alt="">

            {% endif %}
            <div class="absolute w-full bg-gradient-to-l from-neutral-900 to-neutral-900/0 h-max">
        
                <!-- Top Menu -->
                <div id="nav-bar" class="fixed left-1/2 -translate-x-1/2 z-20 container rounded-b-2xl flex justify-between mx-auto px-5 py-3">
                    <div class="flex relative">
                        <img src="{% static 'images/site.png' %}" alt="">

                        <ul class="hidden items-center lg:flex">
                            <li class="active mx-1">
                                <button id="dropdownHoverButton1" data-dropdown-toggle="dropdownHover1" data-dropdown-trigger="hover"  data-dropdown-offset-skidding="100" data-dropdown-placement="right" class="flex items-center" type="button">
                                    <i class="fa-duotone fa-solid fa-grid-2 ml-1"></i>دسته بندی ها
                                    <svg class="w-2.5 h-2.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                                    </svg>
                                </button>
                                
                                <div id="dropdownHover1" class="hidden flex rounded-3xl shadow w-[900px] p-7 blur-d">
                                    <ul class="border-l border-gray-200 pl-7">
                                        <li class="p-6 hover:bg-[#000101] rounded-2xl" id="sites-part">بخش ها</li>
                                        <li class="p-6 hover:bg-[#000101] rounded-2xl" id="movie-gener">ژانر فیلم ها</li>
                                        <li class="p-6 hover:bg-[#000101] rounded-2xl" id="serial-gener">ژانر سریال ها</li>
                                    </ul>
                                    <div class="grid grid-cols-5" id="sites-part-section">
                                        <a class="p-5" href="{% url 'media:serials' %}"><p class="p-1 border-r-4 border-amber-500 hover:text-amber-500">سریال ها({{ serial_counts }})</p></a>
                                        <a class="p-5" href="{% url 'media:movies' %}"><p class="p-1 border-r-4 border-amber-500 hover:text-amber-500">فیلم ها({{ movie_counts }})</p></a>
                                    </div>
                                    <div class="grid grid-cols-5 hidden" id="movie-gener-section">
                                        {% for ganer in movie_ganers %}
                                        <a class="px-2" href="{% url 'media:movie-ganer' ganer.slug %}"><p class="p-1 border-r-4 border-amber-500 hover:text-amber-500">{{ ganer.name }} ({{ ganer.count }})</p></a>
                                        {% endfor %}
                                    </div>
                                    <div class="grid grid-cols-5 hidden" id="serial-gener-section">
                                        {% for ganer in serial_ganers %}
                                        <a class="p-5" href="{% url 'media:serial-ganer' ganer.slug %}"><p class="p-1 border-r-4 border-amber-500 hover:text-amber-500">{{ ganer.name }} ({{ ganer.count }})</p></a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </li>
                            <li class="active: mx-2"><a href="{% url 'media:actors' %}">هنرمندان</a></li>
                            <li class="mx-2">پخش آنلاین</li>
                            <li class="mx-2"><a href="{% url 'dashboard:buy-subscription' %}">خرید اشتراک</a></li>
                            {% if request.user.is_authenticated %}
                            <li class="mx-2"><a href="{% url 'logout' %}">خروج</a></li>
                            {% else %}
                            <li class="mx-2"><a href="{% url 'login' %}">ورود</a></li>
                            {% endif %}
                            <li class="mx-2"><a href="{% url 'media:contact-us' %}">تماس با ما</a></li>
                        </ul>
                    </div>
        
                    <div class="flex items-center">
                        <img class="h-8 bg-black/50 p-1 rounded-2xl mr-3" src="{% static 'images/search.png' %}" alt="">
                        <img class="h-8 bg-black/50 p-1 rounded-2xl mr-3" src="{% static 'images/notification.png' %}" alt="">
                        
                        {% if request.user.is_authenticated %}
                        <button id="dropdownHoverButton" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover" class="flex items-center" type="button">
                            {{ request.user }}
                            <svg class="w-2.5 h-2.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                            </svg>
                            <img class="h-11 rounded-2xl mr-3" src="{% if request.user.gender == 'male' %} {% static 'images/male.png' %} {% else %} {% static 'images/female.png' %} {% endif %}" alt="">
                        </button>

                        <!-- User Dropdown -->
                        <div id="dropdownHover" class="hidden rounded-3xl shadow w-60 p-1 blur-d z-10">
                            <ul class="py-2 text-sm px-2" aria-labelledby="dropdownHoverButton">
                                <li>
                                    <div class="flex">
                                        <img class="mr-1" src="{% static 'images/сrown.png' %}" alt="" srcset="">
                                        <p>اشتراک باقی مانده: <div class="flex px-0.5 mr-1 rounded-lg bg-stone-400/25">{% if special_time <= 0 %}<span class="bg-red-500/30 rounded-lg ml-0.5">غیرفعال</span>{% else %}<span class="bg-green-400 text-green-700 rounded-lg ml-0.5">{{ special_time }} روز</span><a href="#" class="hover:text-amber-500">تمدید</a> {% endif %}</div></p>
                                    </div>
                                </li>
                                <hr class="mt-3">
                                <a href="{% url 'dashboard:dashboard' %}">
                                    <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                        <div class="flex items-center">
                                            <i class="fa-duotone fa-solid fa-grid-2 fa-lg ml-2"></i>
                                            ورود به داشبورد
                                        </div>
                                    </li>
                                </a>
                                <a href="{% url 'dashboard:profile' %}">
                                    <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                        <div class="flex items-center">
                                            <i class="fa-solid fa-gear fa-lg ml-2"></i>
                                            ویرایش اطلاعات
                                        </div>
                                    </li>
                                </a>
                                <a href="{% url 'dashboard:request' %}">
                                    <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                        <div class="flex items-center">
                                            <i class="fa-regular fa-square-plus fa-lg ml-2"></i>
                                            درخواست فیلم/سریال
                                        </div>
                                    </li>
                                </a>
                                <a href="{% url 'dashboard:ticket' %}">
                                    <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                        <div class="flex items-center">
                                            <i class="fa-light fa-messages-question fa-lg ml-2"></i>
                                            تیکت ها
                                        </div>
                                    </li>
                                </a>
        
                                <hr class="mt-2">
        
                                <a href="{% url 'logout' %}">
                                    <li class="mt-1 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                        <div class="pb-2 flex items-center justify-center">
                                            <i class="fa-solid fa-arrow-right-from-bracket fa-lg ml-2"></i>
                                            خروج
                                        </div>
                                    </li>
                                </a>
                            </ul>
                        </div>
                        {% endif %}

                    </div>

                </div>

                {% block top_section %} {% endblock %}
            </div>
            {% block mobile_detail_section %} {% endblock %}

        </div>
    </div>

    {% block content %} {% endblock %}

    <!-- Footer -->
    <div class="flex mt-5 py-5 bg-[#000c1e]">
        <div class="container flex justify-start mx-auto">
            <ul class="flex flex-col md:flex-row space-y-2 space-x-5 ">
                <li class="ml-5 hover:text-amber-500 text-black p-2.5 w-fit bg-white rounded-full "><a href="#">top</a></li>
                <li class="hover:text-amber-500"><a href="#">خرید اشتراک</a></li>
                <li class="hover:text-amber-500"><a href="#">پخش آنلاین</a></li>
                <li class="hover:text-amber-500"><a href="#">سوالات متداول</a></li>
                <li class="hover:text-amber-500"><a href="#">قوانین</a></li>
                <li class="hover:text-amber-500"><a href="#">تماس با ما</a></li>
            </ul>
        </div>
    </div>

    <!-- Script for add bg blur in Top menu -->
    <script>
        const parts = document.getElementById('sites-part');
        const movieGener = document.getElementById('movie-gener');
        const serialGener = document.getElementById('serial-gener');
        
        const partsSection = document.getElementById('sites-part-section');
        const movieGenerSection = document.getElementById('movie-gener-section');
        const serialGenerSection = document.getElementById('serial-gener-section');

        parts.addEventListener('mouseover', function(){
            partsSection.classList.remove('hidden');
            movieGenerSection.classList.add('hidden');
            serialGenerSection.classList.add('hidden');
        })
        movieGener.addEventListener('mouseover', function(){
            partsSection.classList.add('hidden');
            movieGenerSection.classList.remove('hidden');
            serialGenerSection.classList.add('hidden');
        })
        serialGener.addEventListener('mouseover', function(){
            partsSection.classList.add('hidden');
            movieGenerSection.classList.add('hidden');
            serialGenerSection.classList.remove('hidden');
        })
        window.addEventListener('scroll', function(){
            const nav = document.getElementById('nav-bar');
            
            if (window.scrollY > 0) {
                nav.classList.add('blur-d');
            } else {
                nav.classList.remove('blur-d');
            }
        })
    </script>
    <script src="{% static 'js/flowbite.min.js.js' %}"></script>
</body>
</html>

templates/movieserial/filter.html
{% extends 'movieserial/base_site.html' %}
{% block content %}
    
    <div class="h-24"></div>
    <div class="container mx-auto px-3">
        <form action="" method="get" class="lg:flex justify-between">
            
            <p class="text-2xl my-4 text-center lg:m-0 font-bold">
                {% if page_name == 'movie-ganer' %} سینمایی: {% elif page_name == 'serial-ganer' %}سریال:‌ {% elif page_name == 'acotrs' %}بازیگران: {% endif %}
                {{ ganer.name }}
                {% if page_name == 'serial-ganer' %}({{ ganer.serial_set.count }}){% elif page_name == 'movie-ganer' %}({{ ganer.movie_set.count }}){% endif %}</p>
            {% if page_name in 'serial-ganer,movie-ganer' %}
            <div>
                <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-y-7">
                    <div class="relative outline outline-2 p-1 w-fit rounded-lg outline-gray-500 mx-0 lg:mr-5">
                        <!-- <input type="text" name="" id="" class="px-2 py-2 bg-black rounded-lg"> -->
                        <label class="absolute bg-black -top-4 right-3 px-2">مرتب سازی</label>
                        <Select name="ordering" class="px-2 py-2 bg-black rounded-lg w-60">
                            <option value="newest">جدیدترین</option>
                            <option value="imdb_point">امتیاز IMDB</option>
                            <option value="release_year">سال انتشار</option>
                        </Select>
                    </div>
                    <div class="relative outline outline-2 p-1 w-fit rounded-lg outline-gray-500 mx-0 lg:mr-5">
                        <label class="absolute bg-black -top-4 right-3 px-2">امتیاز IMDB</label>
                        <!-- <input type="text" name="" id="" class="px-2 py-2 bg-black rounded-lg"> -->
                        <Select name="point" class="px-2 py-2 bg-black rounded-lg w-60">
                            <option value="all">همه</option>
                            <option value="9">بالای 9</option>
                            <option value="8">بالای 8</option>
                            <option value="7">بالای 7</option>
                            <option value="6">بالای 6</option>
                            <option value="5">بالای 5</option>
                            <option value="4">بالای 4</option>
                            <option value="3">بالای 3</option>
                        </Select>
                    </div>
                    {% if page_name not in 'serial-ganer,movie-ganer' %}
                    <div class="relative outline outline-2 p-1 w-fit rounded-lg outline-gray-500 mx-0 lg:mr-5">
                        <label class="absolute bg-black -top-4 right-3 px-2">ژانر</label>
                        <!-- <input type="text" name="" id="" class="px-2 py-2 bg-black rounded-lg"> -->
                        <Select name="ganer" id="ganer-list" class="px-2 py-2 bg-black rounded-lg w-60">
                            <option value="all">همه</option>
                        </Select>
                    </div>
                    {% endif %}
                    <div class="outline outline-2 inline-block p-1 w-fit rounded-lg outline-gray-500 mx-0 lg:mr-5">
                        <button class="px-2 py-2 inline-block w-fit bg-black rounded-lg">جست و حو</button>
                    </div>
                </div>
                <script>
                    
                    {% if page_name not in 'serial-ganer,' %}
                    const generList = [
                        {% for ganer in ganers %}
                        {name: '{{ ganer.name }}', slug: '{{ ganer.slug }}'},
                        {% endfor %}
                        {name: 'همه', slug: 'all'},
                    ]

                    const target = document.getElementById('ganer-list');
                    for (let i = 0; i<generList.length; i++){
                        target.innerHTML += '<option class="" value="SLUG">GENER</option>'.replace('SLUG', generList[i].slug).replace('GENER', generList[i].name)
                    }
                    {% endif %}
                </script>
            </div>
            {% endif %}
        </form>
        <div>
            
            <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7 gap-5 mt-4">
                {% if page_name in 'serial-ganer,serials' %}
                    {% for object in objects %}
                        {% include 'components/media.html' with media=object media_type='serial' %}
                    {% empty %}
                        <p></p>
                        <p></p>
                        <p class="text-center p-3 rounded-lg ">هیچی پیدا نکردم</p>
                    {% endfor %}
                {% elif page_name in 'movie-ganer,movies' %}
                    {% for object in objects %}
                        {% include 'components/media.html' with media=object media_type='movie' %}
                    {% endfor %}
                {% elif page_name == 'actors' %}
                    {% for actor in objects %}
                        {% include 'components/actor.html' with actor=actor %}
                    {% endfor %}
                {% endif %}
            </div>
            
            
            {% include 'components/paginator.html' with objects=objects %}
            
        </div>
        <div class="h-32"></div>
        
    </div>
{% endblock %}