movieserial/urls.py
from django.urls import path
from .views import (SerialDetailsView, MovieDetailsView, SerialGanerView, MovieGanerView, ActorsView, ActorDetailsView, ContactUsView,
    AllMoviesView, AllSerialsView
    )


app_name = 'media'
urlpatterns = [
    path('movie/', AllMoviesView.as_view(), name='movies'),
    path('serial/', AllSerialsView.as_view(), name='serials'),
    path('serial/<str:slug>/', SerialDetailsView.as_view(), name='serial-details'),
    path('movie/<str:slug>/', MovieDetailsView.as_view(), name='movie-details'),
    path('serial/ganer/<str:slug>/', SerialGanerView.as_view(), name='serial-ganer'),
    path('movie/ganer/<str:slug>/', MovieGanerView.as_view(), name='movie-ganer'),
    path('actors', ActorsView.as_view(), name='actors'),
    path('actor/<int:id>/', ActorDetailsView.as_view(), name='actor-details'),
    path('contact-us/', ContactUsView.as_view(), name='contact-us'),
]

netmovie/urls.py
# For statics
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from user.views import LoginView, SignupView, logoutView
from movieserial.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='home'),
    path('logout', logoutView, name='logout'),
    path('dashboard/', include('user.urls')),
    path('', include('movieserial.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

# import Views
from .views import (ProfileView, ChangePasswordView, BuySubscriptionView, HistorySubscriptionView, TicketSupportView,
                    TicketDetailsView, RequestView, DashboardView)


app_name = 'dashboard'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('buy-subscription/', BuySubscriptionView.as_view(), name='buy-subscription'),
    path('history-subscription/', HistorySubscriptionView.as_view(), name='history-subscription'),
    path('ticket/', TicketSupportView.as_view(), name='ticket'),
    path('ticket/<int:ticket_id>/', TicketDetailsView.as_view(), name='ticket-details'),
    path('request/', RequestView.as_view(), name='request'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

movieserial/models.py
from django.db import models
from django.contrib.contenttypes import fields, models as c_model
from django.core.validators import MaxValueValidator, MinValueValidator
from user.models import User
from functools import partial


def folder_finder(instance, filename, folder):
    class_name = instance.__class__.__name__.lower()
    _type = 'movies' if class_name == 'movie' else 'serials'
    folder_path = f'images/{_type}/{folder}/{filename}'
    return folder_path


class Actor(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    photo = models.ImageField(upload_to='images/actor/', blank=True, verbose_name='عکس')
    imdb_link = models.URLField(blank=True, verbose_name='ادرس imdb')

    class Meta:
        verbose_name = 'بازیگر'
        verbose_name_plural = 'بازیگر ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Ganers(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    slug = models.SlugField(unique=True, verbose_name='اسلاگ')

    class Meta:
        verbose_name = 'ژانر'
        verbose_name_plural = 'ژانر ها'
        ordering = ['name']


    def __str__(self):
        return self.name


class BaseMedia(models.Model):
    name = models.CharField(max_length=300, verbose_name='نام')
    persian_name = models.CharField(max_length=200, verbose_name='نام فارسی')
    ganers = models.ManyToManyField(Ganers, verbose_name='ژانر ها')
    description = models.CharField(max_length=500, blank=True, verbose_name='درباره')
    stars = models.ManyToManyField(Actor, blank=True, verbose_name='ستارگان')
    info = models.CharField(max_length=200, blank=True, verbose_name='جزیات')
    baner = models.ImageField(upload_to=partial(folder_finder, folder='baner'), verbose_name='عکس فیلم')
    background_baner = models.ImageField(upload_to=partial(folder_finder, folder='backgrounds'), blank=True, verbose_name='بک گراند')
    slug = models.SlugField(unique=True, verbose_name='اسلاگ')
    trailer = models.URLField(blank=True, verbose_name='تریلر')
    online_play = models.URLField(blank=True, verbose_name='لینک تماشای انلاین')
    imdb_link = models.URLField(blank=True, verbose_name='لینک(ارجاع به  imdb)')
    year_create = models.IntegerField(verbose_name='سال ساخت')
    duration = models.TimeField(verbose_name='زمان')
    release_date = models.DateTimeField(verbose_name='زمان پخش')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')
    is_subtitle = models.BooleanField(default=True, verbose_name='زیرنویس')
    is_sound_translate = models.BooleanField(default=False, verbose_name='دوبله')
    point = models.DecimalField(
                                max_digits=4,
                                decimal_places=2,
                                validators=[
                                    MaxValueValidator(10.0,),
                                    MinValueValidator(0.0)
                                    ],
                                verbose_name='امتیاز imdb'
                                )


    class Meta:
        abstract = True
        ordering = ['name']


    def __str__(self):
        return self.name


class DownloadLink(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    link = models.URLField(verbose_name='لینک دانلود مستقیم')
    size = models.BigIntegerField(verbose_name='اندازه')
    is_subtitle = models.BooleanField(default=True, verbose_name='زیرنویس')
    subtitle_types = (('nosub', 'بدون زیرنویس'), ('subsoft', 'subsoft'),)
    subtitle_type = models.CharField(max_length=150, choices=subtitle_types, verbose_name='نوع زیرنویس')
    is_persian_sound = models.BooleanField(verbose_name='صدای فارسی')

    class Meta:
        verbose_name = 'لینک دانلود'
        verbose_name_plural = 'لینک های دانلود'
        ordering = ['id']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Quality(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    episodes = models.ManyToManyField(DownloadLink, verbose_name='قسمت ها')

    class Meta:
        verbose_name = 'کیفیت'
        verbose_name_plural = 'کیفیت ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Section(models.Model):
    name = models.CharField(max_length=150, verbose_name='نام')
    qualitys = models.ManyToManyField(Quality, verbose_name='کیفیت ها')
    status_types = (('creating', 'درحال تولید'),('completed', 'تکمیل شده'), ('canceled', 'کنسل شده'))
    status = models.CharField(max_length=150, choices=status_types, verbose_name='وضعیت')

    class Meta:
        verbose_name = 'بخش'
        verbose_name_plural = 'بخش ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Serial(BaseMedia):
    sections = models.ManyToManyField(Section, blank=True, verbose_name='بخش ها')
    last_episod = models.CharField(max_length=200, verbose_name='آخرین قسمت')
    last_section = models.ForeignKey(Section, blank=True, null=True, on_delete=models.CASCADE, related_name='last_section', verbose_name='آخرین فصل')

    class Meta:
        verbose_name = 'سریال'
        verbose_name_plural = 'سریال ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class Movie(BaseMedia):
    qualitys = models.ManyToManyField(Quality, verbose_name='کیفیت ها')

    class Meta:
        verbose_name = 'سینمایی'
        verbose_name_plural = 'سینمایی ها'
        ordering = ['name']


    def __str__(self):
        return f'{self.name}: {self.id}'


class BaseComment(models.Model):
    text = models.TextField(verbose_name='متن')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر ارسال کننده')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')
    is_spoil = models.BooleanField(default=False, verbose_name='نظر حاوی اسپویل')



class MovieComment(BaseComment):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name='سینمایی')
    parent_comment = models.ForeignKey('MovieComment', on_delete=models.CASCADE, null=True, blank=True, verbose_name='کامنت پرنت')

    class Meta:
        verbose_name = 'کامنت فیلم'
        verbose_name_plural = 'کامنت های فیلم'


    def __str__(self):
        return f'{self.user.__str__()}: {self.id}'



class SerialComment(BaseComment):
    serial = models.ForeignKey(Serial, on_delete=models.CASCADE, verbose_name='سریال')
    parent_comment = models.ForeignKey('SerialComment', on_delete=models.CASCADE, null=True, blank=True, verbose_name='کامنت پرنت')


    class Meta:
        verbose_name = 'کامنت سریال'
        verbose_name_plural = 'کامنت های سریال'


    def __str__(self):
        return f'{self.user.__str__()}: {self.id}'


class ContactUs(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام')
    phone = models.BigIntegerField(verbose_name='شماره')
    email = models.EmailField(blank=True, verbose_name='ایمیل')
    subject = models.CharField(max_length=200, verbose_name='موضوع')
    message = models.TextField(verbose_name='متن پیام')


    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'تماس با ما'

    def __str__(self):
        return self.name

templates/components/actor.html
{% load static %}
<div class="transition duration-300 hover:scale-110 group">
    <div class="relative w-max">
        <img src="{% if actor.photo %}{{ actor.photo.url }}{% else %}{% static 'images/default-user.png' %}{% endif %}" alt="" class="rounded-2xl transition duration-[400ms] group-hover:brightness-50 w-48 h-72 border-black border group-hover:border-amber-500">

    </div>
    <h6 class="text-center my-3">{{ actor.name }}</h6>
    <a href="{% url 'media:actor-details' actor.id %}" class="text-center mb-2 p-2 pt-1 rounded-lg bg-amber-500 block">جزیات بیشتر</a>
</div>

templates/components/media.html
{% load static %}
<div class="transition duration-300 hover:scale-110 cursor-pointer group" onclick="window.location.href='{% if media_type == "serial" %}{% url "media:serial-details" media.slug %}{% elif media_type == "movie" %}{% url "media:movie-details" media.slug %}{% endif %}'">
    <div class="relative w-max">
        <img src="{{ media.baner.url }}" alt="" class="rounded-2xl transition duration-[400ms] group-hover:brightness-50 w-48 h-72 border-black border group-hover:border-amber-500">
        <div class="absolute flex top-1 right-1">
            {% if media.is_sound_translate %}
            <img src="{% static 'images/microphone.png' %}" alt="" class="bg-black/50 rounded-full p-1 h-7">
            {% endif %}
            {% if media.is_subtitle %}
            <img src="{% static 'images/subtitle.png' %}" alt="" class="bg-black/50 rounded-full p-1 h-7 mr-1">
            {% endif %}
        </div>
        {% if media.online_play != '' %}
        <img src="{% static 'images/play.png' %}" alt="" class="absolute top-1 left-1 bg-black/50 rounded-full p-1 h-7">
        {% endif %}
    </div>

    <div class="absolute bottom-1/2 -translate-y-1/2 opacity-0 transition-opacity duration-[400ms] group-hover:opacity-100">
        <div class="flex">
            {% for ganer in media.ganers.all %}
            <a href="{% if media_type == "serial" %}{% url "media:serial-ganer" ganer.slug %}{% elif media_type == 'movie' %}{% url 'media:movie-ganer' ganer.slug %}{% endif %}" class="bg-white/20 rounded-md p-1 mr-1">{{ ganer.name }}</a>
            {% endfor %}
        </div>
    </div>
    <h6 class="text-center">{{ media.name }}</h6>
    <h6 class="text-center"><span class="text-amber-400">{{ media.point }}/10</span><span class="mx-2">|</span>{{ media.year_create }}</h6>
</div>

templates/components/paginator.html
<div id="pagination" class="flex mt-4 justify-center">
    <a id="first_page{{ perfix|default:'1' }}" href="" class="transition duration-300 px-3.5 py-2 rounded-lg bg-white/20 mx-1 hover:bg-amber-500">first</a>
    {% if objects.has_previous %}
    <a id="previous_page{{ perfix|default:'1' }}" href="" class="transition duration-300 px-3.5 py-2 rounded-lg bg-white/20 mx-1 hover:bg-amber-500">&lt;</a>
    {% endif %}
    <a id="current_page" class="transition duration-300 px-3.5 py-2 rounded-lg bg-amber-500 mx-1 hover:bg-amber-500">{{ objects.number }}</a>
    {% if objects.has_next %}
    <a id="next_page{{ perfix|default:'1' }}" href="" class="transition duration-300 px-3.5 py-2 rounded-lg bg-white/20 mx-1 hover:bg-amber-500">&gt;</a>
    {% endif %}
    <a id="last_page{{ perfix|default:'1' }}" href="" class="transition duration-300 px-3.5 py-2 rounded-lg bg-white/20 mx-1 hover:bg-amber-500">last</a>
</div>

<script>
    function updatePageUrl(baseUrl, pageNumber) {
        const url = new URL(baseUrl);
        url.searchParams.set('page', pageNumber);
        return url.href;
    }

    const currentUrl{{ perfix|default:'1' }} = window.location.href;

    const firstPageNumber{{ perfix|default:'1' }} = 1;
    const nextPageNumber{{ perfix|default:'1' }} = {% if objects.has_next %}{{ objects.next_page_number }}{% else %}null{% endif %};
    
    const previousPageNumber{{ perfix|default:'1' }} = {% if objects.has_previous %}{{ objects.previous_page_number }}{% else %}null{% endif %};
    const lastPageNumber{{ perfix|default:'1' }} = {{ objects.paginator.num_pages }};

    document.getElementById('first_page{{ perfix|default:'1' }}').href = updatePageUrl(currentUrl{{ perfix|default:'1' }}, firstPageNumber{{ perfix|default:'1' }});
    if (nextPageNumber{{ perfix|default:'1' }}) {
        document.getElementById('next_page{{ perfix|default:'1' }}').href = nextPageNumber{{ perfix|default:'1' }} ? updatePageUrl(currentUrl{{ perfix|default:'1' }}, nextPageNumber{{ perfix|default:'1' }}) : '';
    }
    if (previousPageNumber{{ perfix|default:'1' }}) {
        document.getElementById('previous_page{{ perfix|default:'1' }}').href = previousPageNumber{{ perfix|default:'1' }} ? updatePageUrl(currentUrl{{ perfix|default:'1' }}, previousPageNumber{{ perfix|default:'1' }}) : '';
    }
    document.getElementById('last_page{{ perfix|default:'1' }}').href = updatePageUrl(currentUrl{{ perfix|default:'1' }}, lastPageNumber{{ perfix|default:'1' }});

</script>

templates/components/profile-input.html
{% if field.field.widget.input_type != 'radio' %}
    <div class="w-full mx-2 mt-3">
        <label for="{{ field.id_for_label }}" class="mr-3 ">{{ field.label }}</label><!-- mt-3 -->
        <div class="bg-zinc-900/80 mt-1 w-full rounded-xl p-5 flex">
            <i class="fa-light fa-user text-2xl ml-5"></i>
            {{ field }}
        </div>
    </div>

    {% if field.errors %}
        {% for error in field.errors %}
            <p>{{ error }}</p>
        {% endfor %}
    {% endif %}
{% else %}
    <div class="w-full mx-2 mt-3">
        <label for="{{ field.id_for_label }}" class="mr-3 ">{{ field.label }}</label><!-- mt-3 -->
        <div class="bg-zinc-900/80 flex mt-1 w-full rounded-xl p-5 flex">
            <i class="fa-light fa-user text-2xl ml-5"></i>
            <label id="gender1" onclick="choice_item('id_gender_1');add_color(this);" for="id_gender_1" class="px-5 py-1 rounded-lg {% if field.value == 'female' %} bg-amber-400{% endif %}">
                <span style="color: red;">زن</span>
                <input {% if field.value == 'female' %} checked="true" {% endif %} id="id_gender_1" type="radio" name="gender" value="female" class="appearance-none">
            </label>
            <p class="mx-1"></p>
            <label id="gender0" onclick="choice_item('id_gender_0');add_color(this);" for="id_gender_0" class="px-5 py-1 rounded-lg {% if field.value == 'male' %} bg-amber-400{% endif %}">
                <span style="color: red;">مرد</span>
                <input {% if field.value == 'male' %} checked="true" {% endif %} id="id_gender_0" type="radio" name="gender" value="male" class="appearance-none">
            </label>
        </div>
    </div>
    <p id="test">d</p>
    <script>
        function choice_item(el) {
            document.getElementById('id_gender_1').checked = false;
            document.getElementById('id_gender_0').checked = false;
            document.getElementById(el).checked = true;
        }
        function add_color(id) {
            document.getElementById('gender1').classList.remove('bg-amber-400');
            document.getElementById('gender0').classList.remove('bg-amber-400');
            id.classList.add('bg-amber-400');
        }
    </script>
{% endif %}

templates/components/replay_comment.html
{% load static %}
{% for replay in comments %}
<div class="p-3 mr-10e">
    <div class="flex">
        <img class="h-12 rounded-xl ml-1" src="{% if replay.user.gender == 'female' %}{% static 'images/female.png' %}{% else %}{% static 'images/male.png' %}{% endif %}" alt="">
        <strong class="ml-1">{{ replay.user }}</strong>
        <p>{{ replay.created_at|date:'Y/m/d H:i:s' }}</p>
    </div>
    <p class="px-3.5">{{ replay.text }}</p>
    <div class="flex justify-between">
        <p onclick="sednReplay({{ replay.id }}, '{{ replay.user }}')">پاسخ</p>
        <div class="flex">
            <img src="{% static 'images/like.png' %}" alt="" class="h-7 mb-2">            <p>--</p>
            <span class="border mx-2"></span>
            <p>--</p>
            <img src="{% static 'images/dislike.png' %}" alt="" class="h-7 mt-2">
        </div>
    </div>
</div>

<hr>
{% if replay.serialcomment_set.exists %}
<div style="margin-right: 50px;">
{% include 'components/replay_comment.html' with comments=replay.serialcomment_set.all %}
</div>
{% endif %}
{% if replay.moviecomment_set.exists %}
<div style="margin-right: 50px;">
{% include 'components/replay_comment.html' with comments=replay.moviecomment_set.all %}
</div>
{% endif %}
{% endfor %}