netmovie/urls.py
# For statics
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import include, path
from user.views import LoginView, SignupView, logoutView
from movieserial.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('', HomeView.as_view(), name='home'),
    path('logout', logoutView, name='logout'),
    path('dashboard/', include('user.urls')),
    path('', include('movieserial.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

# import Views
from .views import (ProfileView, ChangePasswordView, BuySubscriptionView, HistorySubscriptionView, TicketSupportView,
                    TicketDetailsView, RequestView, DashboardView)


app_name = 'dashboard'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('buy-subscription/', BuySubscriptionView.as_view(), name='buy-subscription'),
    path('history-subscription/', HistorySubscriptionView.as_view(), name='history-subscription'),
    path('ticket/', TicketSupportView.as_view(), name='ticket'),
    path('ticket/<int:ticket_id>/', TicketDetailsView.as_view(), name='ticket-details'),
    path('request/', RequestView.as_view(), name='request'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.exceptions import ValidationError


class PhoneNumber(models.Model):
    number = models.CharField(max_length=11, verbose_name="شماره تلفن")

    class Meta:
        verbose_name = 'شماره تلفن'
        verbose_name_plural = 'شماره تلفن ها'


    def __str__(self):
        return str(self.number)


class Manager(UserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not password:
            raise ValidationError('The password must be set.')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    gender_types = (("male", "مرد"), ("female", "زن"))
    gender = models.CharField(choices=gender_types, max_length=6, default="male")
    number = models.ForeignKey(PhoneNumber, on_delete=models.CASCADE, blank=True, null=True, verbose_name="شماره")
    special_time = models.DateTimeField(blank=True, null=True, verbose_name="مدت اشتراک")
    objects = Manager()

    class Meta:
        verbose_name = "کاربر"
        verbose_name_plural = "کاربرها"


    def __str__(self):
        return self.get_full_name() if self.get_full_name() else self.username


class Pakage(models.Model):
    title = models.CharField(max_length=150, verbose_name="موضوع")
    image = models.ImageField(blank=True, upload_to='images', verbose_name="عکس")
    description = models.TextField(verbose_name="جزیات")
    price = models.PositiveIntegerField(verbose_name="قیمت")
    is_active = models.BooleanField(default=True, verbose_name="فعال")
    discountPrice = models.PositiveIntegerField(default=0, verbose_name="قیمت تخفیف خورده")
    dates = models.IntegerField(verbose_name="مدت بسته")

    class Meta:
        verbose_name = 'بسته'
        verbose_name_plural = 'بسته ها'
        ordering = ['price']


    def get_price(self):
        return self.price - self.discountPrice

    def __str__(self):
        return self.title


class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر")
    pakage = models.ForeignKey(Pakage, on_delete=models.SET_NULL, null=True, verbose_name="پکیج")
    price = models.PositiveIntegerField(verbose_name="قیمت")
    days = models.IntegerField(verbose_name="مدت اشتراک")
    actived_at = models.DateTimeField(auto_now_add=True, verbose_name="زمان خرید")

    class Meta:
        verbose_name = 'اشتراک'
        verbose_name_plural = 'اشتراک ها'


    def __str__(self):
        return f"{self.user}: {self.price}"


class Ticket(models.Model):
    departeman_types = (('finance and sales', 'مالی و فروش'), ('technical', 'پشتیبانی فنی'))
    title = models.CharField(max_length=200, verbose_name="عنوان تیکت")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='سازنده')
    departeman = models.CharField(choices=departeman_types, max_length=17, default='finance and sales', verbose_name='دپارتمان')
    update_at = models.DateTimeField(auto_now_add=True)
    status_types = (('pending', 'در انتظار پاسخ'), ('answered', 'پاسخ داده'), ('closed', 'بسته شده'))
    status = models.CharField(max_length=8, choices=status_types, default='pending', verbose_name='وضعیت')

    class Meta:
        verbose_name = 'تیکت'
        verbose_name_plural = 'تیکت ها'
        ordering = ['-update_at']

    def __str__(self):
        return f'{self.user}: {self.title[:50]} ...'


class MessageSupport(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, verbose_name='تیکت')
    message = models.TextField(verbose_name = 'پیام')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='فرستنده')

    class Meta:
        verbose_name = 'پیام پشتیبانی'
        verbose_name_plural = 'پیام های پشتیبانی'


    def __str__(self):
        return self.sender.__str__()


class Request(models.Model):
    request_types = (('movie', 'فیلم'), ('serial', 'سریال'))
    request_type = models.CharField(max_length=7, choices=request_types, default='movie', verbose_name='نوع درخواست')
    name = models.CharField(max_length=150, verbose_name='نام فیلم یا سریال')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    year = models.IntegerField(verbose_name='سال انتشار')
    date = models.DateField(auto_now_add=True, verbose_name='زمان')
    link = models.URLField(blank=True, null=True, verbose_name='لینک')
    status_types = (('pending', 'در صف'), ('accept', 'قبول شده'), ('reject', 'رد شده'))
    status = models.CharField(max_length=7, choices=status_types, default='pending', verbose_name='وضعیت')
    message = models.CharField(max_length=300, verbose_name='پیام', blank=True)

    class Meta:
        verbose_name = 'درخواست'
        verbose_name_plural = 'درخواست ها'


    def __str__(self):
        return f'{self.user}: {self.name}'

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from .forms import LoginForm, SignupForm, UpdateProfileForm, PhoneNumberForm, TicketForm, MessageSupportForm, RequestForm
from django.db.models import F
import datetime
import pytz
from django.utils import timezone
from .utils import get_ip, get_left_special_time
from django.core.paginator import Paginator


# Auth imports
from django.contrib.auth import authenticate, login, logout
from .mixins import RedirectAuthenticatedUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings

from .models import MessageSupport, Request, User, Pakage, Subscription, Ticket


class LoginView(RedirectAuthenticatedUser, View):
    template_name = 'movieserial/auth.html'
    context = {'page_name': 'ورود',
               'form': LoginForm()}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                next_url = request.GET.get('next', None) # to prevent auto logout after login(next)
                return redirect(next_url if next_url and next_url != '/logout' else reverse('home'))
            else:
                self.context.update({'msg': 'کاربری با این مشخصات یافت نشد'})
        else:
            self.context.update({'msg': 'فرم کامل نشده', 'form': form})
        return render(request, self.template_name, self.context)


class SignupView(RedirectAuthenticatedUser, View):
    template_name = 'movieserial/auth.html'
    context = {
        'page_name': 'ثبت نام',
        'form': SignupForm()
    }

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            if settings.LOGIN_AFTER_SIGNUP:
                login(request, user)
                next_url = request.GET.get('next', None) # to prevent auto logout after login(next)
            return redirect(next_url if next_url and next_url != '/logout' else reverse('home'))
        else:
            self.context.update({'form': form})
        return render(request, self.template_name, self.context)


class ProfileView(LoginRequiredMixin, View):
    template_name = 'user/profile.html'

    def setup(self, request, *args, **kwargs):
        # LoginRequiredMixin dose not work with setup method
        super().setup(request, *args, **kwargs)
        if request.user.is_authenticated:
            self.context = {
                'user_form': UpdateProfileForm(instance=request.user),
                'phone_form': PhoneNumberForm(user=request.user),
                'page_name': 'profile',
                'title_page': 'آپدیت پروفایل | نت موی',
                'current_time': timezone.now(),
            'special_time': get_left_special_time(request.user)
            }
        else:
            return redirect(reverse('login'))

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        user_form = UpdateProfileForm(request.POST, instance=request.user)
        phone_form = PhoneNumberForm(request.POST, user=request.user)

        if user_form.is_valid():
            email = user_form.cleaned_data['email']
            if User.objects.filter(email = email).exclude(id=request.user.id).exists():
                user_form.add_error('email', 'ایمیل تکراری است')
            else:
                user_form.save()
        self.context['user_form'] = user_form

        if phone_form.has_changed():
            if phone_form.is_valid() and request.user.number is None:
                phone = phone_form.save()
                user = User.objects.get(pk=request.user.pk)
                user.number = phone
                user.save()
            self.context['phone_form'] = phone_form
        return render(request, self.template_name, self.context)


class ChangePasswordView(LoginRequiredMixin, View):
    template_name = 'user/change-password.html'
    def setup(self, request, *args, **kwargs):
        self.context = {
                'page_name': 'change password',
                'title_page': 'تغییر پسورد | نت موی',
                'current_time': timezone.now(),
                'special_time': get_left_special_time(request.user)
            }
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        last_password = request.POST.get('last_password')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        user = authenticate(request, username = request.user.username, password = last_password)
        if user is not None:
            if password1 == password2:
                user.set_password(password1)
                user.save()
                return redirect(reverse('login'))
            else:
                self.context['msg'] = 'پسورد ها با هم یکی نیستند'
        else:
            self.context['msg'] = 'پسورد قبلی اشتباه است'
        return render(request, self.template_name, self.context)


class BuySubscriptionView(LoginRequiredMixin, View):
    template_name = 'user/buy-subscription.html'

    def get(self, request, *args, **kwargs):
        context = {
            'page_name': 'buy subscription',
            'title_page': 'خرید اشتراک | نت موی',
            'pakages': Pakage.objects.filter(is_active = True),
            'current_time': timezone.now(),
            'special_time': get_left_special_time(request.user)
        }
        pakage_id = request.GET.get('pakage', None)

        if pakage_id:
            pakage = get_object_or_404(Pakage, is_active = True, id=pakage_id)
            Subscription.objects.create(user = request.user, pakage = pakage, price = pakage.get_price(), days = pakage.dates)
            time = datetime.timedelta(days=pakage.dates)
            user = User.objects.get(id=request.user.id)
            if user.special_time and user.special_time > timezone.now():
                user.special_time = F('special_time') + time
            else:
                user.special_time = datetime.datetime.now(tz=pytz.timezone('Asia/Tehran')) + time
            user.save()

            request.user.refresh_from_db()
            context.update({
                'msg': 'success',
                'daytes': pakage.dates,
                'special_time': get_left_special_time(request.user)
            })
        return render(request, self.template_name, context)


class HistorySubscriptionView(LoginRequiredMixin, View):
    template_name = 'user/history-subscription.html'

    def get(self, request, *args, **kwargs):
        p = Paginator(Subscription.objects.filter(user=request.user).order_by('actived_at'), 20)
        page = request.GET.get('page', 1)

        context = {
            'page_name': 'history subscription',
            'title_page': 'سابقه خرید | نت موی',
            'special_time': get_left_special_time(request.user),
            'page': p.page(page),
            'current_time': timezone.now(),
        }
        return render(request, self.template_name, context)


class TicketSupportView(LoginRequiredMixin, View):
    template_name = 'user/tickets.html'

    def setup(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            self.context = {
                'page_name': 'ticket',
                'title_page': 'تیکت پشتیبانی | نت موی',
                'special_time': get_left_special_time(request.user),
                'current_time': timezone.now(),
                'tickets': Ticket.objects.filter(user = request.user),
                'form': TicketForm(user=request.user),
            }
        super().setup(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)
    
    def post(self, request, *args, **kwargs):
        form = TicketForm(request.POST, user = request.user)
        if form.is_valid():
            form.save()
            self.context['msg'] = 'success'
        else:
            self.context['form'] = form
        return render(request, self.template_name, self.context)


class TicketDetailsView(LoginRequiredMixin, View):
    template_name = 'user/ticket-details.html'

    def setup(self, request, ticket_id, *args, **kwargs):
        if request.user.is_authenticated:
            self.ticket = get_object_or_404(Ticket, id = ticket_id)
            self.context = {
                # 'page_name': '',
                'title_page': f'ticket: {self.ticket.title} | نت موی',
                'special_time': get_left_special_time(request.user),
                'current_time': timezone.now(),
                'messages': MessageSupport.objects.filter(ticket = self.ticket),
                'form': MessageSupportForm(),
                'ticket': self.ticket
            }
        return super().setup(request, ticket_id, *args, **kwargs)

    def get(self, request, ticket_id, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, ticket_id, *args, **kwargs):
        form = MessageSupportForm(request.POST, ticket = self.ticket, user = request.user)
        if form.is_valid():
            form.save()
        else:
            self.context['form'] = form

templates/user/base_panel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ title_page }}</title>
        <link rel="stylesheet" href="{% static 'css/main_site.css' %}">
        {% block styles %} {% endblock %}
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/all.css">
    
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-duotone-solid.css">
    
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-thin.css">
    
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-solid.css">
    
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-regular.css">
    
        <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.6.0/css/sharp-light.css">
    </head>
<body dir="rtl" class="text-slate-100 bg-zinc-900">
    <div class="flex flex-col">
        <!-- Top menu -->
        <div class="flex justify-between px-2 py-3">
            
            <div class="hidden w-full lg:flex lg:flex-row items-center">
                <div class="md:w-1/5">
                    <img src="{% static 'images/site-icon.png' %}" alt="">
                </div>
                <ul class="flex">
                    <li class="hover:text-amber-500 mx-0.5 p-1"><a href="/">صفحه اصلی</a></li>
                    <li class="hover:text-amber-500 mx-0.5 p-1"><a href="{% url 'dashboard:buy-subscription' %}">خرید اشتراک</a></li>
                    <li class="hover:text-amber-500 mx-0.5 p-1"><a class="{% if page_name == 'profile' %}text-amber-600{% endif %}" href="{% url 'dashboard:profile' %}">پروفایل</a></li>
                    <li class="hover:text-amber-500 mx-0.5 p-1"><a href="{% url 'dashboard:ticket' %}">پشتیبانی</a></li>
                </ul>
            </div>
            
            <a href="/" class="lg:hidden bg-zinc-900 p-3 py-2.5 self-center rounded-full">
                <i class="fa-regular fa-house"></i>
            </a>

            <img class="lg:hidden" src="{% static 'images/site-icon.png' %}" alt="">

            <!-- user info -->
            <div class="flex lg:hidden items-center mr-5 group">
                            
                <button id="dropdownHoverButton" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover" class="flex items-center" type="button">
                    {{ request.user }}
                    <svg class="w-2.5 h-2.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
                    <img class="h-11 rounded-2xl mr-3" src="{% static 'images/male.png' %}" alt="">
                </button>
                    
                <!-- Dropdown menu -->
                <div id="dropdownHover" class="hidden rounded-3xl shadow w-60 p-1 blur-d z-10">
                    <ul class="py-2 text-sm px-2" aria-labelledby="dropdownHoverButton">
                        <li>
                            <div class="flex">
                                <img class="mr-1" src="{% static 'images/сrown.png' %}" alt="" srcset="">
                                <p>اشتراک باقی مانده: <div class="flex px-0.5 mr-1 rounded-lg bg-stone-400/25"><span class="bg-green-400 text-green-700 rounded-lg ml-0.5">{{ special_time }} روز</span><a href="#" class="hover:text-amber-500">تمدید</a></div></p>
                            </div>
                        </li>
                        <hr class="mt-3">
                        <a href="{% url 'dashboard:dashboard' %}">
                            <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                <div class="flex items-center">
                                    <i class="fa-duotone fa-solid fa-grid-2 fa-lg ml-2"></i>
                                    ورود به داشبورد
                                </div>
                            </li>
                        </a>
                        <a href="{% url 'dashboard:profile' %}">
                            <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                <div class="flex items-center">
                                    <i class="fa-solid fa-gear fa-lg ml-2"></i>
                                    ویرایش اطلاعات
                                </div>
                            </li>
                        </a>
                        <a href="{% url 'dashboard:request' %}">
                            <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                <div class="flex items-center">
                                    <i class="fa-regular fa-square-plus fa-lg ml-2"></i>
                                    درخواست فیلم/سریال
                                </div>
                            </li>
                        </a>
                        <a href="{% url 'dashboard:ticket' %}">
                            <li class="my-1 py-3 pt-2 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                <div class="flex items-center">
                                    <i class="fa-light fa-messages-question fa-lg ml-2"></i>
                                    تیکت ها
                                </div>
                            </li>
                        </a>

                        <hr class="mt-2">

                        <a href="{% url 'logout' %}">
                            <li class="mt-1 hover:bg-gray-400/20 rounded-md hover:text-amber-400">
                                <div class="pb-2 flex items-center justify-center">
                                    <i class="fa-solid fa-arrow-right-from-bracket fa-lg ml-2"></i>
                                    خروج
                                </div>
                            </li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>

        <div class="flex">
            <!-- Sid menu -->
            <div class="md:w-1/5 lg:flex lg:flex-col hidden">
                <div class="h-64 flex flex-row justify-center items-center">
                    <div class="flex flex-col items-center">
                        <img class="rounded-3xl mx-auto w-24 h-24 outline outline-4 outline-offset-8 outline-amber-500 hover:outline-white transition-all duration-[400ms] ease-in-out" src="{% static 'images/male.png' %}" alt="">
                        <p class="mt-2 font-bold text-2xl">{{ request.user.get_full_name|default:request.user.username }}</p>
                        <p class="text-gray-300">{{ request.user.number.number|default:'شماره تلفن تنظیم نشده' }}</p>
                    </div>
                </div>

                <ul class="px-4">
                    <a href="{% url 'dashboard:dashboard' %}" class="{% if page_name == 'dashboard' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-grid-2 text-2xl ml-2"></i>
                        <p>داشبورد</p>
                    </a>
                    <a href="{% url 'dashboard:buy-subscription' %}" class="{% if page_name == 'buy subscription' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-crown text-2xl ml-2"></i>
                        <p>خرید اشتراک {% if request.user.special_time > current_time %}<span class="bg-green-600 rounded-xl px-2 py-1.5">فعال</span>{% else %}<span class="bg-red-600 rounded-xl px-2 py-1.5">غیرفعال</span>{% endif %}</p>
                    </a>
                    <a href="{% url 'dashboard:profile' %}" class="{% if page_name == 'profile' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-user text-2xl ml-2"></i>
                        <p>پروفایل</p>
                    </a>
                    <a href="{% url 'dashboard:history-subscription' %}" class="{% if page_name == 'history subscription' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-regular fa-file-lines text-2xl ml-2"></i>
                        <p>سابقه خرید</p>
                    </a>
                    <a href="{% url 'dashboard:change-password' %}" class="{% if page_name == 'change password' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-lock text-2xl ml-2"></i>
                        <p>تغییر پسورد</p>
                    </a>
                    <a href="{% url 'dashboard:request' %}" class="{% if page_name == 'request' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-bullhorn text-2xl ml-2"></i>
                        <p>درخواست فیلم و سریال</p>
                    </a>
                    <a href="{% url 'dashboard:ticket' %}" class="{% if page_name == 'ticket' %}bg-zinc-800{% endif %} px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-comment text-2xl ml-2"></i>
                        <p>تیکت و پشتیابنی</p>
                    </a>
                    <a href="{% url 'logout' %}" class="px-2 p-5 my-1 rounded-xl flex items-center hover:bg-zinc-800 transition-all duration-[400ms]">
                        <i class="fa-light fa-rigth-from-bracket text-2xl ml-2"></i>
                        <p>خروج</p>
                    </a>
                </ul>
            </div>
            
            {% block content %} {% endblock %}
        </div>
    </div>
    <script src="{% static 'js/flowbite.min.js.js' %}"></script>
</body>
</html>

templates/user/ticket-details.html
{% extends 'user/base_panel.html' %}
{% load static %}
{% block content %}
            <duv class="lg:w-4/5 w-full  bg-black rounded-tr-[50px]">
                <div class="flex justify-between px-4 my-3">
                    <p>مشاهده تیکت ها :<span class="mr-1"> {{ ticket.title }}</span></p>
                    <div class="flex">
                        <i class="fa-light fa-calendar-days ml-1"></i>
                        <p class="text-sm">{{ current_time|date:'l H:i:s Y/m/s' }}</p>
                    </div>
                </div>

                <div class="mt-2 p-5">
                    <div class="mt-3 bg-zinc-900 rounded-2xl">
                        <div class="flex justify-between rounded-t-2xl p-3 bg-zinc-800">
                            <p>گفتگو با پشتیبانی</p>
                            <div class="flex">
                                <div class="flex items-center">
                                    <i class="fa-light fa-folder ml-1"></i>
                                    <p>{{ ticket.get_departeman_display }}</p>
                                </div>
                                <p class="mr-4">
                                    <i class="fa-ligtht far far fa-clock ml-1"></i>
                                    آخرین بروزرسانی:
                                    <span>{{ ticket.update_at|date:'Y/m/d H:i:s' }}</span>
                                </p>
                            </div>
                        </div>
                        <div class="p-5">
                            {% for msg in messages %}
                            <div {% if msg.sender != request.user %} dir="ltr" {% endif %} class="flex justify-start mt-3">
                                <img src="{% if request.user.image %}{{ request.user.image.url }}{% elif request.user.gender == 'male' %}{% static 'images/male.png' %}{% elif request.user.gender == 'female' %}{% static 'images/female.png' %}{% endif %}" width="50px" height="50px" alt="" class="rounded-full self-center mx-2">
                                <div class="p-3 bg-zinc-950 rounded-xl">{{ msg.message }}</div>
                            </div>
                            {% endfor %}
                        </div>
                        <form method="post" class="bg-zinc-950 rounded-xl p-3 mt-4 mx-2 flex">
                            {% csrf_token %}
                            <div class="flex">
                                <button class="btn-amber animation" type="submit">ارسال</button>
                                <div class="border-l border-gray-500" style="width: 4px;"></div>
                            </div>
                            <textarea class="input-dark simple-input bg-zinc-900 mr-2 px-2 rounded-xl" placeholder="متن رو اینجا بنویس ..." name="message" required id="id_message"></textarea>
                        </form>
                        {% for error in form.message.errors %}
                            <p class="text-red-500 bg-red-400/30 rounded-lg p-1 m-2">{{ error }}</p>
                        {% endfor %}
                        <div style="height: 10px;"></div>
                    </div>
                </div>
            </duv>
{% endblock %}